### ISSUE TITLE
Я выполнил задание

### ISSUE THREAD

**Issue by KorobovSV** [MIEE-ACS/domashnee-zadanie-no1-KorobovSV#1]
Лабораторная работа №1, вариант №4, Коробов С.В.

**Comment by d-makarenko** [comment]
https://github.com/MIEE-ACS/domashnee-zadanie-no1-KorobovSV/blob/95fa2866cdb1ea4e233b077b9f8e37bb4460d122/Zad1_4/Zad1_4/Program.cs#L21

Почему массив имеет 4 элемента?

**Comment by KorobovSV** [comment]
подправил

**Comment by d-makarenko** [comment]
Зачет
